# Generated by Django 3.1.4 on 2024-06-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('disease', models.CharField(max_length=255)),
                ('blood_group', models.CharField(max_length=255)),
                ('c_date', models.CharField(max_length=255)),
            ],
        ),
    ]
